# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
          - dependency-name: "io.github.git-commit-id:git-commit-id-maven-plugin"
            versions: ["5.x", "6.x", "7.x"]
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "Examples/cHolograms" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "Examples/cLegacyCombat" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "Examples/cMiniMap" # Location of package manifests
    schedule:
      interval: "daily" 
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "Examples/cStaffModules" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "Examples/cWaypoints" # Location of package manifests
    schedule:
      interval: "daily"
