# Permissions for CheatBreaker commands
cheatbreaker:
  commands:
    message: "cheatbreaker.message"
    title: "cheatbreaker.title"

# Toggles if the server will kick someone for not using CheatBreaker.
kick:
  enabled: true
  message: "&cOffline CheatBreaker is required to play on &6&lServer name&r&c!\n&cYou can download it from OfflineCheatBreaker.com"

# Toggle if the server should message someone for using CheatBreaker
auth-message:
  enabled: true
  message: "&aYou are now verified using &r&c&lCheat&r&f&lBreaker"

# Waypoints which will be sent to the client when
# they join the server.
waypoints:
  - name: &9Spawn
    domain: spawn
    location:
      x: 125
      y: 64
      z: 672
    forced: true
  - name: &aEnd Arena Spawn
    domain: 'arena.The End'
    location:
      x: 100
      y: 70
      z: 100
    forced: false

# Toggles if the CheatBreaker client will hide
# numbers next to the scoreboard. Values:
# FORCED_OFF: Numbers are hidden and cannot be shown by the user
# FORCED_ON: Numbers are shown and cannot be hidden by the user
# NEUTRAL: The user can toggle number visibility freely
scoreboardNumbers: FORCED_OFF