# Permissions for CheatBreaker commands
permissions:
  message: "cheatbreaker.message"
  title: "cheatbreaker.title"

# Toggles if the server will kick someone for not using CheatBreaker.
kick:
  enabled: true
  message: "&cCheatBreaker is required to play on &6&lServer name&r&c!\n&cYou can download it from CheatBreaker.net"

# Toggle if the server should message someone for using CheatBreaker
auth-message:
  enabled: true
  message: "&aYou are now verified using &r&c&lCheat&r&f&lBreaker"