name: ${project.name}
version: ${git.commit.id.abbrev}
description: CheatBreaker Bukkit API
author: CheatBreaker & Offline CheatBreaker Development Teams
website: https://offlinecheatbreaker.com
main: com.cheatbreaker.api.CheatBreakerAPI
load: STARTUP
commands:
  cb:
    aliases: [cbplayer, cheatbreaker, cheatbreakerplayer]
  cbm:
    aliases: [cbmessage, cheatbreakermessage]
  cbt:
    aliases: [cbtitle, cheatbreakertitle]