name: ${project.name}
version: ${git.commit.id.abbrev}
description: CheatBreaker Bukkit API
author: CheatBreaker & Offline CheatBreaker Development Teams
website: https://offlinecheatbreaker.com
main: com.cheatbreaker.api.CheatBreakerAPI
load: STARTUP
commands:
  cb:
    aliases: [cbplayer, cheatbreaker, cheatbreakerplayer]
    description: Check if a player is using CheatBreaker
  cbm:
    aliases: [cbmessage, cheatbreakermessage]
    description: Send a message to all CheatBreaker players
  cbt:
    aliases: [cbtitle, cheatbreakertitle]
    description: Send a title text to all CheatBreaker players