name: Build API

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      # Get the latest commit ID
      - id: commit
        uses: prompt/actions-commit-hash@v3
      # Clone the repo & its submodules
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      # Setup Java & Maven
      - name: Install Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
      # Compile the project
      - name: Compile the NetHandler
        run: cd NetHandler && mvn clean install
      - name: Compile the API
        run: mvn clean install
      # Create a release with the compiled API jar
      - uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "target/CheatBreakerAPI.jar"
          tag: ${{ steps.commit.outputs.short }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
